feat: Implement GLPI user connection - EXO-67852
exo-addons/glpi-integration pull request #10
Opened 2023-12-11 16:26 UTC by hakermi

Implement GLPI user connection frontend

2023-12-11 16:56 UTC, rdenarie requested changes

2023-12-11 16:56 UTC, rdenarie commented on glpi-integration-services/src/main/java/org/exoplatform/glpi/service/GLPIServiceImpl.java
> +      LOG.error("remote_service={} operation={} parameters=\"user token:{}, status=ko "
Can we display both parameters ? userIdentityId (or username if possible) AND user token

2023-12-12 07:32 UTC, hakermi commented on glpi-integration-services/src/main/java/org/exoplatform/glpi/service/GLPIServiceImpl.java
> +      LOG.error("remote_service={} operation={} parameters=\"user token:{}, status=ko "
The initSession takes in parameter only the userToken, so IMO we can't add the identityid as parameter to just log it without being used in the function isn't it ?

2023-12-12 07:39 UTC, rdenarie approved these changes

2023-12-12 07:52 UTC, merged