feat: Implement GLPI user connection backend - EXO-67845
exo-addons/glpi-integration pull request #7
Opened 2023-12-08 15:32 UTC by hakermi

GLPI user connection backend

2023-12-08 16:38 UTC, rdenarie requested changes

2023-12-11 08:21 UTC, hakermi commented
@rdenarie PR updated

2023-12-11 09:15 UTC, rdenarie requested changes

2023-12-11 09:15 UTC, rdenarie commented on glpi-integration-services/src/main/java/org/exoplatform/glpi/service/GLPIServiceImpl.java
> +    }
Why do you separate the 2 errors ? 
could we have only one catch, and log.error with remote_service into ?

2023-12-11 09:15 UTC, rdenarie commented on glpi-integration-services/src/main/java/org/exoplatform/glpi/service/GLPIServiceImpl.java
> +    }
Same remark

2023-12-11 09:31 UTC, hakermi commented on glpi-integration-services/src/main/java/org/exoplatform/glpi/service/GLPIServiceImpl.java
> +    }
because , when we catch the HttpResponseException we have info such as status code reasonPhrase, and when we catch the Exception globally we will not have these info. 
So when we have a HttpResponseException we log the info and when it's another exception we log it

2023-12-11 09:32 UTC, hakermi commented on glpi-integration-services/src/main/java/org/exoplatform/glpi/service/GLPIServiceImpl.java
> +    }
https://github.com/exo-addons/glpi-integration/pull/7#discussion_r1422175490

2023-12-11 09:48 UTC, rdenarie approved these changes

2023-12-11 09:51 UTC, merged